Add very basic smoke test so deployment script can work [#160827147]

diff --git a/ci/build-docker-e2e-image b/ci/build-docker-e2e-image
--- a/ci/build-docker-e2e-image
+++ b/ci/build-docker-e2e-image
@@ -1,24 +1,32 @@
 #!/usr/bin/env bash
 
-function validate_arg() {
-  local name=${1}
-  local value=${2}
+set -e
+set -x
 
-  if [ -z ${value} ]; then
-    echo "Must specify value for ${name}." >&2
-    exit 1
-  else
-    echo -n ${value}
-  fi
-}
+# This script packages the end-to-end test module into a Docker image that runs the tests against
+# an arbitrary deployment of this service, specified by the E2E_TEST_URI environment variable.
+# The contents of /target are captured by the CI system after the tests have run, which makes
+# report generation possible.
 
-set -ex
-
-cd $(dirname $0)/..
+# The Docker image we build is tagged with the string passed in as the first argument to this script.
 
 # This script is invoked during CI build with the following arguments:
-target_image_name=$(validate_arg "target image name" ${1})
-app_name=$(validate_arg "app name" ${2})
-app_version=$(validate_arg "app version" ${3})
+target_image_name=$1
+app_name=$2
+app_version=$3
+
+pushd e2e-tests
+../mvnw versions:set -DnewVersion=${app_version}
+../mvnw clean package -DskipTests=true
+../mvnw versions:revert
+popd
+
+# This script does all its staging in a directory called target for easy cleanup and effective .gitignore.
+dockerWorkspace=ci/e2e-tests/target
+mkdir -p ${dockerWorkspace}
+
+cp -rp mvnw .mvn ${dockerWorkspace}/
+cp -p ci/e2e-tests/e2e-exec-pom.xml ${dockerWorkspace}/pom.xml
+cp -p e2e-tests/target/gatekeeper-e2e-tests-${app_version}.jar ${dockerWorkspace}/e2e-tests.jar
 
 (cd ci/e2e-tests && docker build -t ${target_image_name} .)
